### ISSUE TITLE
Optional chaining syntax error in the first example

### ISSUE THREAD

**Issue by nielsboecker** [davidkpiano/frontend-masters-xstate-workshop#8]
Hi, thanks for the great course, enjoying it a lot!

I just wanted to share a little confusion I encountered. For the first example, I copied the code [from the slides](https://slides.com/davidkhourshid/xstate-workshop?token=NuUhf7a4#/12). I ran into issues with the optional chaining syntax:

```bash
Server running at http://localhost:1234
🚨  .../fem_xstate/src/00/index.js:37:4: Unexpected token (37:4)
  35 |   return machine
  36 |     .states[state]?
> 37 |     .on?.[event]
     |    ^
  38 |     || state;
  39 | }
```

I soon found out that the issue is the formatting here: The syntax doesn't seem to support line breaks after the question mark. After I put it all on one line, it worked just fine. However, having not worked with this new syntax in JS before, I first suspected some misconfiguration of Babel and went off to try and change that. Perhaps, to provide more clarity, the formatting on the slides could be adjusted, or a comment could be added.

**Comment by davidkpiano** [comment]
I fixed it!
